app:
  service:
    ticketmaster:
      url: https://app.ticketmaster.com/discovery/v2
      apiKey: JDEgJlXoAaxGAuqmctaPsNAHL7s5nSC3
    yelp:
      url: https://api.yelp.com/v3
      clientID: YD7r-X10cbUKFVQ1ItN1Qw
      apiKey: MOQq90DN4LxgCv3uYFvXgoTAMUeyfUJgz3r1TTwxxe1pdRz59tfeNkjaaC50Jpqn0oCBH61gwc37nprJ7vcD6BhnZsyWxFyvoxEK2MPQmQFQIy3getO0UZZlAwXqWnYx
  server:
    port: 8080
  mysql:
    host: localhost
    database: hackathon_jci
    username: admin
    password: 123456
